from openai import OpenAI

from config import OPENROUTER_API_KEY


client = OpenAI(
    api_key=OPENROUTER_API_KEY,
    base_url="https://openrouter.ai/api/v1"
)


def generate_response(message: str) -> str:

    response = client.chat.completions.create(
        model="openai/gpt-oss-20b:free",
        messages=[
            {
                "role": "user",
                "content": message
            }
        ],
        max_tokens=1000
    )

    content = response.choices[0].message.content
    return content if content is not None else "No response generated by model."